# Sign actions.

name: Sign

# Trigger on push or everyday 10:21 AM @ "Asia/Shanghai" Timezone (UTC+8).
on:
  push:
    branches: [ master ]
    paths:
      - 'auto_sign.js'
  schedule:
    - cron:  '16 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: tyde7/yqxx_auto_sign@master
        with:
          args: yarn
      - name: Test
        uses: tyde7/yqxx_auto_sign@master
        env: 
          JWC_USERNAME: ${{ secrets.JWC_USERNAME }}
          JWC_PASSWORD: ${{ secrets.JWC_PASSWORD }}
          WECHAT_ROBOT_HOOK: ${{ secrets.WECHAT_ROBOT_HOOK }}
          CURRENT_POS: ${{ secrets.WECHAT_ROBOT_HOOK }}
          SIM_LAT: ${{ secrets.SIM_LAT }}
          SIM_LONG: ${{ secrets.SIM_LONG }}
        with:
          args: yarn test
        timeout-minutes: 30
